### ISSUE TITLE
ASL Glossing

### ISSUE THREAD

**Issue by thecookiemomma** [philphilphil/obsidian-standardform#3]
Is there a way to use this to type ASL glossing?  (American sign language literal sign by sign markers).   
(Example below)
![image](https://github.com/user-attachments/assets/a63a3123-82de-422c-a055-35c7e805b949)

**Comment by philphilphil** [comment]
Unfortunately not. Do I understand this correctly, that you have some text, and for one or multiple parts of that text you want an "overline" and write something above that line. I found this other example:
![grafik](https://github.com/user-attachments/assets/25115e04-bba1-475b-9c1e-7af8e4af492d)

Some parts of this plugin could for sure be used to create something like this, but it will be a bit more challenging since it needs to fit together above each other but if you like we can work together on this. Do you have vision, how this should work in Markdown or within a code block?

I could imagine something like this, as example for the first sentence of the screenshot:
`YEAR-PAST[ ME(POSS)] HOUSE ROOMS[WHA(wh)]T W[HITE fsA-L(eyebrows up)]-L`
Putting the text that should be overlined into square brackets, then the text of the overline into normal brackets, or the other way around, or maybe you have a better idea :)

**Comment by thecookiemomma** [comment]
That would work. I just would like to have some sort of system to be able to write out the gloss when I interpret. Something like that would absolutely work.

**Comment by philphilphil** [comment]
Sounds good, i created a new repository for this https://github.com/philphilphil/obsidian-asl-glossing and will start working on it :)

**Comment by thecookiemomma** [comment]
Thank you!
